-- CATEGORY - 'ELETRONICS'
INSERT INTO CATEGORY (ID, NAME) VALUES (NEXTVAL('CATEGORY_SEQUENCE'), 'ELETRONICS');

-- PRODUCT - CATEGORY 'ELETRONICS'
INSERT INTO PRODUCT (ID, NAME, CATEGORY) VALUES (NEXTVAL('PRODUCT_SEQUENCE'), 'ACCESSORIES & SUPPLIES', 	CURRVAL('CATEGORY_SEQUENCE'));
INSERT INTO PRODUCT (ID, NAME, CATEGORY) VALUES (NEXTVAL('PRODUCT_SEQUENCE'), 'CAMERA & PHOTO', 			CURRVAL('CATEGORY_SEQUENCE'));
INSERT INTO PRODUCT (ID, NAME, CATEGORY) VALUES (NEXTVAL('PRODUCT_SEQUENCE'), 'CAR & VEHICLE ELECTRONICS', 	CURRVAL('CATEGORY_SEQUENCE'));
INSERT INTO PRODUCT (ID, NAME, CATEGORY) VALUES (NEXTVAL('PRODUCT_SEQUENCE'), 'CELL PHONES & ACCESSORIES', 	CURRVAL('CATEGORY_SEQUENCE'));

-- CATEGORY - 'SOFTWARE'
INSERT INTO CATEGORY (ID, NAME) VALUES (NEXTVAL('CATEGORY_SEQUENCE'), 'SOFTWARE');

-- PRODUCT - CATEGORY 'SOFTWARE'
INSERT INTO PRODUCT (ID, NAME, CATEGORY) VALUES (NEXTVAL('PRODUCT_SEQUENCE'), 'ACCOUNTING & FINANCE', 	CURRVAL('CATEGORY_SEQUENCE'));
INSERT INTO PRODUCT (ID, NAME, CATEGORY) VALUES (NEXTVAL('PRODUCT_SEQUENCE'), 'ANTIVIRUS & SECURITY', 	CURRVAL('CATEGORY_SEQUENCE'));
INSERT INTO PRODUCT (ID, NAME, CATEGORY) VALUES (NEXTVAL('PRODUCT_SEQUENCE'), 'BUSINESS & OFFICE', 		CURRVAL('CATEGORY_SEQUENCE'));
INSERT INTO PRODUCT (ID, NAME, CATEGORY) VALUES (NEXTVAL('PRODUCT_SEQUENCE'), 'DESIGN & ILLUSTRATION', 	CURRVAL('CATEGORY_SEQUENCE'));
