-- DROP OBJECTS
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS CATEGORY;

DROP SEQUENCE IF EXISTS CATEGORY_SEQUENCE;
DROP SEQUENCE IF EXISTS PRODUCT_SEQUENCE;

-- SEQUENCES
CREATE SEQUENCE CATEGORY_SEQUENCE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PRODUCT_SEQUENCE  START WITH 1 INCREMENT BY 1;

-- TABELAS
CREATE TABLE CATEGORY (
	ID	 INT PRIMARY KEY,
	NAME VARCHAR(30)
);

CREATE TABLE PRODUCT (
	ID   INT PRIMARY KEY,
	NAME VARCHAR(30),

	CATEGORY INT,

	FOREIGN KEY (CATEGORY) REFERENCES CATEGORY(ID)
);